language: swift
osx_image: xcode11.6
env:
- DESTINATION="OS=13.0,name=iPhone 11" SCHEME="XLProductName" SDK=iphonesimulator

before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
- cd Framework-iOS && carthage update --platform iOS
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- xcodebuild clean build -project XLProductName.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
- xcodebuild test -project XLProductName.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
